# Generated by Django 2.2 on 2020-12-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20201210_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('LL', 'Lowest'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('HH', 'Highest')], max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('X', 'Incomplete'), ('I', 'In-Progress'), ('C', 'Complete')], max_length=200),
        ),
    ]
