# Generated by Django 2.2 on 2020-12-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20201210_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='images/checklist.png', upload_to='images/'),
        ),
    ]
