# Generated by Django 3.2 on 2021-04-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20210422_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In-Progress'), (3, 'Complete')], default=1),
        ),
    ]
