# Generated by Django 3.2.8 on 2021-10-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_itemquantity_location_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='images/inventory.jpg', upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='ItemQuantity',
        ),
    ]
