# Generated by Django 3.2.8 on 2021-10-27 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20211027_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='items.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='room_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='items.room'),
        ),
    ]
