# Generated by Django 3.2.8 on 2021-10-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_auto_20211027_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
