# Generated by Django 3.2.8 on 2021-10-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_auto_20211028_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(default='images/closet.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(default='images/rooms.jpg', upload_to='images/'),
        ),
    ]
