# Generated by Django 3.2.8 on 2021-11-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_auto_20211028_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='images/inventory.jpg', upload_to='./'),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(default='images/closet.jpg', upload_to='./'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(default='images/rooms.jpg', upload_to='./'),
        ),
    ]
