# Generated by Django 3.2.8 on 2021-11-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_auto_20211104_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='inventory.jpg', upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(default='closet.jpg', upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(default='rooms.jpg', upload_to='user_images/'),
        ),
    ]
